/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : fsm.sm
 */

#include "play_sm.h"

#define getOwner(fsm) (fsm)->_owner

#define ENTRY_STATE(state) \
    if ((state)->Entry != NULL) { \
        (state)->Entry(fsm); \
    }

#define EXIT_STATE(state) \
    if ((state)->Exit != NULL) { \
        (state)->Exit(fsm); \
    }

static void doorState_condition_to_close(struct fsmContext *const fsm)
{
    getState(fsm)->Default(fsm);
}

static void doorState_condition_to_open(struct fsmContext *const fsm)
{
    getState(fsm)->Default(fsm);
}

static void doorState_Default(struct fsmContext *const fsm)
{
    State_Default(fsm);
}

#define MainMap_open_condition_to_close doorState_condition_to_close
#define MainMap_open_condition_to_open doorState_condition_to_open
#define MainMap_open_Default doorState_Default
#define MainMap_close_condition_to_close doorState_condition_to_close
#define MainMap_close_condition_to_open doorState_condition_to_open
#define MainMap_close_Default doorState_Default
#define MainMap_DefaultState_condition_to_close doorState_condition_to_close
#define MainMap_DefaultState_condition_to_open doorState_condition_to_open

void MainMap_open_Entry(struct fsmContext *const fsm)
{
    struct door *ctxt = getOwner(fsm);

    door_enter_act_push(ctxt);
}

void MainMap_open_Exit(struct fsmContext *const fsm)
{
    struct door *ctxt = getOwner(fsm);

    door_exit_act_push(ctxt);
}

#undef MainMap_open_condition_to_close
static void MainMap_open_condition_to_close(struct fsmContext *const fsm)
{

    EXIT_STATE(getState(fsm));
    setState(fsm, &MainMap_close);
    ENTRY_STATE(getState(fsm));

}

const struct doorState MainMap_open = {
    MainMap_open_Entry,
    MainMap_open_Exit,
    MainMap_open_condition_to_close,
    MainMap_open_condition_to_open,
    MainMap_open_Default,
    0
};

int door_enter_act_push(struct door *ctxt)
{
    printf("the door enter act push\r\n");
}

int door_exit_act_push(struct door *ctxt)
{
    printf("the door exit act push\r\n");
}
int door_entry_act_put(struct door *ctxt)
{
    printf("the door enter act put\r\n");
}
int door_exit_act_put(struct door *ctxt)
{
    printf("the door exit act put\r\n");
}


void MainMap_close_Entry(struct fsmContext *const fsm)
{
    struct door *ctxt = getOwner(fsm);

    door_entry_act_put(ctxt);
}

void MainMap_close_Exit(struct fsmContext *const fsm)
{
    struct door *ctxt = getOwner(fsm);

    door_exit_act_put(ctxt);
}

#undef MainMap_close_condition_to_open
static void MainMap_close_condition_to_open(struct fsmContext *const fsm)
{

    EXIT_STATE(getState(fsm));
    setState(fsm, &MainMap_open);
    ENTRY_STATE(getState(fsm));

}

const struct doorState MainMap_close = {
    MainMap_close_Entry,
    MainMap_close_Exit,
    MainMap_close_condition_to_close,
    MainMap_close_condition_to_open,
    MainMap_close_Default,
    1
};

#ifdef NO_FSM_SM_MACRO
void fsmContext_Init(struct fsmContext *const fsm, struct door *const owner)
{
    FSM_INIT(fsm, &MainMap_open);
    fsm->_owner = owner;
}

void fsmContext_EnterStartState(struct fsmContext *const fsm)
{
    ENTRY_STATE(getState(fsm));
}

void fsmContext_condition_to_close(struct fsmContext *const fsm)
{
    const struct doorState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "condition_to_close");
    state->condition_to_close(fsm);
    setTransition(fsm, NULL);
}

void fsmContext_condition_to_open(struct fsmContext *const fsm)
{
    const struct doorState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "condition_to_open");
    state->condition_to_open(fsm);
    setTransition(fsm, NULL);
}
#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
